version: '2'
services:
  elasticsearch:
    build: services/elasticsearch
    container_name: elasticsearch
    volumes:
      - /var/lib/docker/kontor/elasticsearch/data:/data
#      - ./elasticsearch/config:/data/config
    environment:
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200

  rabbitmq:
    build: services/rabbitmq
    container_name: rabbitmq

  kontorcore:
    build: services/kontor-core
    container_name: kontor-core
    links:
      - elasticsearch
      - rabbitmq
    volumes:
      - ./services/kontor-core:/usr/src/app/
    ports:
      - 8080:4000

volumes:
  easticsearch_data:
    driver: local
