swagger: "2.0"
info:
  version: "0.1."
  title: Kontor App
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http

consumes:
  - application/json
produces:
  - application/json
paths:
  /posts/{id}:
    x-swagger-router-controller: archiveController
    get:
      description: Returns the post with the provided `id`
      operationId: findArchivePost
      parameters:
        - name: id
          in: path
          description: The id of the post
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Post"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Updates the post with the provided `id`
      operationId: updatePost
      parameters:
        - name: id
          in: path
          description: The id of the post
          required: true
          type: string

        - name: post
          in: body
          required: true
          schema:
            $ref: "#/definitions/Post"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Post"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes the post with the provided `id`
      operationId: deletePost
      parameters:
        - name: id
          in: path
          description: The id of the post
          required: true
          type: string
      responses:
        "200":
          description: Success
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /posts:
    x-swagger-router-controller: archiveController
    post:
      description: Creates a post
      operationId: createPost
      parameters:
        - name: post
          in: body
          required: true
          schema:
            $ref: "#/definitions/Post"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Post"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      description: Returns the posts
      operationId: filterArchivePosts
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              posts:
                type: array
                items:
                  $ref: "#/definitions/Post"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /inbox:
    x-swagger-router-controller: inboxController
    post:
      description: Add an inbox post
      operationId: addPostToInbox
      parameters:
        - name: post
          in: body
          required: true
          schema:
            $ref: "#/definitions/Post"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Post"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      description: Returns the posts of the inbox
      operationId: filterInboxPosts
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              posts:
                type: array
                items:
                  $ref: "#/definitions/Post"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /inbox/{id}:
    x-swagger-router-controller: inboxController
    get:
      description: Returns the post with the provided `id`
      operationId: findInboxPost
      parameters:
        - name: id
          in: path
          description: The id of the post
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Post"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /inbox/{id}/accept:
    x-swagger-router-controller: inboxController
    put:
      description: Accepts an inbox post with the provided `id`
      operationId: acceptInboxPost
      parameters:
        - name: id
          in: path
          description: The id of the post
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Post"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /inbox/{id}/reject:
    x-swagger-router-controller: inboxController
    put:
      description: Rejects an inbox post with the provided `id`
      operationId: rejectInboxPost
      parameters:
        - name: id
          in: path
          description: The id of the post
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Post"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
definitions:
  Post:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the post
      title:
        type: string
      description:
        type: string
      url:
        type: string
      rating:
        type: integer
      createdAt:
        type: integer
        format: int64

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
